name: flutter_calculator_demo
description: A flutter calculator demo.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  extended_text: ^10.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  function_tree: ^0.8.13
  provider: ^6.0.5
  window_manager: ^0.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true